# Generated by Django 6.0.3 on 2026-03-19 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('completed_attempts', models.PositiveIntegerField(default=0)),
                ('total_questions_answered', models.PositiveIntegerField(default=0)),
                ('total_correct_answers', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('highest_score', models.FloatField(default=0.0)),
                ('lowest_score', models.FloatField(default=100.0)),
                ('total_time_spent', models.PositiveIntegerField(default=0, help_text='Total seconds spent on all attempts')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_analytics',
            },
        ),
    ]
