from rest_framework.decorators import api_view, permission_classes, throttle_classes
import logging
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework.response import Response
from rest_framework.pagination import PageNumberPagination

from .serializers import (
    QuizCreateSerializer,
    QuizSerializer,
    QuizListSerializer
)
from common.services.quiz_service import (
    create_quiz_with_questions,
    get_published_quizzes,
    get_quiz_detail,
    get_user_quizzes,
    publish_quiz
)
from common.utils.permissions import IsAdminRole

logger = logging.getLogger(__name__)


from common.utils.throttles import QuizCreateThrottle

@api_view(['POST'])
@permission_classes([IsAuthenticated, IsAdminRole])
@throttle_classes([QuizCreateThrottle])
def create_quiz_view(request):
    """
    POST /api/quizzes/
    Admin only — creates a quiz and generates questions via AI.
    This may take 10-30 seconds due to AI generation.
    """
    serializer = QuizCreateSerializer(data=request.data)

    if not serializer.is_valid():
        return Response(
            {'error': True, 'details': serializer.errors},
            status=status.HTTP_400_BAD_REQUEST
        )

    try:
        quiz = create_quiz_with_questions(
            user=request.user,
            validated_data=serializer.validated_data
        )
        return Response({
            'error': False,
            'message': 'Quiz created successfully. Questions generated by AI.',
            'data': QuizSerializer(quiz).data
        }, status=status.HTTP_201_CREATED)

    except Exception as e:
        logger.error(f'Quiz creation failed: {str(e)}')
        return Response(
            {'error': True, 'message': 'Quiz creation failed.', 'details': str(e)},
            status=status.HTTP_500_INTERNAL_SERVER_ERROR
        )

from django.core.cache import cache
from django.conf import settings

@api_view(['GET'])
@permission_classes([AllowAny])
def list_quizzes_view(request):
    """
    GET /api/quizzes/
    Public — lists all published quizzes with pagination.
    Supports ?topic=python and ?difficulty=easy filters.
    """
    topic = request.query_params.get('topic', '')
    difficulty = request.query_params.get('difficulty', '')
    page = request.query_params.get('page', '1')
    cache_key = f'quiz_list_{topic}_{difficulty}_{page}
    
    cached = cache.get(cache_key)
    if cached:
        return Response(cached)
    quizzes = get_published_quizzes()

    if topic:
        quizzes = quizzes.filter(topic__icontains=topic)
    if difficulty:
        quizzes = quizzes.filter(difficulty=difficulty)

    # Pagination
    paginator = PageNumberPagination()
    paginator.page_size = 10
    page_data= paginator.paginate_queryset(quizzes, request)

    serializer = QuizListSerializer(page, many=True)
    response_data = {
        'error': False,
        'data': serializer.data
    }

    # Store in cache
    cache.set(cache_key, response_data, settings.CACHE_TTL['quiz_list'])

    return paginator.get_paginated_response(response_data)


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def quiz_detail_view(request, quiz_id):
    """
    GET /api/quizzes/<quiz_id>/
    Returns full quiz with questions (correct answers hidden).
    """
    try:
        quiz = get_quiz_detail(quiz_id)
    except Exception:
        return Response(
            {'error': True, 'message': 'Quiz not found.'},
            status=status.HTTP_404_NOT_FOUND
        )

    return Response({
        'error': False,
        'data': QuizSerializer(quiz).data
    })


@api_view(['GET'])
@permission_classes([IsAuthenticated, IsAdminRole])
def my_quizzes_view(request):
    """
    GET /api/quizzes/my-quizzes/
    Admin only — returns all quizzes created by the logged-in admin.
    """
    quizzes = get_user_quizzes(request.user)
    serializer = QuizListSerializer(quizzes, many=True)
    return Response({
        'error': False,
        'data': serializer.data
    })


@api_view(['POST'])
@permission_classes([IsAuthenticated, IsAdminRole])
def publish_quiz_view(request, quiz_id):
    """
    POST /api/quizzes/<quiz_id>/publish/
    Admin only — publishes a draft quiz.
    """
    try:
        quiz = publish_quiz(quiz_id, request.user)
        return Response({
            'error': False,
            'message': f'Quiz "{quiz.title}" is now published.',
            'data': QuizListSerializer(quiz).data
        })
    except Quiz.DoesNotExist:
        return Response(
            {'error': True, 'message': 'Quiz not found.'},
            status=status.HTTP_404_NOT_FOUND
        )
    except (PermissionError, ValueError) as e:
        return Response(
            {'error': True, 'message': str(e)},
            status=status.HTTP_400_BAD_REQUEST
        )